development:
  adapter: postgresql
  encoding: unicode
  database: timetrack_development
  host: localhost
  pool: 5
  username: postgres
  password: password

test:
  adapter: postgresql
  encoding: unicode
  database: timetrack_test
  host: localhost
  pool: 5
  username: postgres
  password: password
  
production: 
  adapter: postgresql
  encoding: unicode
  database: timetrack
  host: localhost
  pool: 5
  username: postgres
  password: password